#!/usr/bin/env bash

# Downloads a bunch of files into the current directory
# -----------------------------------------------------
# This uses my favorite aria2c settings. It took a while to figure them out, so I thought I'd make a little
# script out of it.

EXE=aria2c
STATS=.stats

command -v $EXE >/dev/null 2>&1 || { echo >&2 "I'm afraid this script won't be of much use to you if you don't have $EXE."; exit 1; }

MIN_ARGS=1
E_BADARGS=5
if [ $# -lt $MIN_ARGS ]
then
  echo "Usage: `basename $0` <file containing links>"
  exit $E_BADARGS
fi

LINKS="$1"

$EXE --input-file="$LINKS" --allow-overwrite=true --auto-file-renaming=false --conditional-get=true --max-concurrent-downloads=25 --max-connection-per-server=5 --remote-time=true --split=5 --http-accept-gzip=true --console-log-level=notice --file-allocation=none --human-readable=true --summary-interval=10 --uri-selector=adaptive --server-stat-if="$STATS" --server-stat-of="$STATS" --enable-http-pipelining=true --auto-save-interval=10 --disk-cache=1024M --seed-time=0
