#!/usr/bin/env bash

# Copyright (C) 2013 Thomas Dalling
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

compress() {
	
	if [ ! -d "$1" ]
	then
		echo "$1 does not seem to be a directory. You're asking me to do something strange."
		exit -1
	fi
	
	if [ -d "$1/.git" ]
	then
		echo "There's already a .git directory in $1. I refuse to do something dangerous."
		exit -1
	fi
	
    TARPATH="$(pwd)/$(basename "$1").gitar"

    cd "$1"
    git init
    git add -A
    git commit -m "making a gitar repo"

    git gc --aggressive

    cd .git
    tar cjf "$TARPATH" .
    cd ..
    rm -Rf .git

    ls -lh "$TARPATH"
}

decompress() {
    TARPATH="$(pwd)/$1"
    OUTPUTPATH="$(basename "$1" .gitar)"

	if [ -d "$OUTPUTPATH/.git" ]
	then
		echo "There's already a .git directory in $OUTPUTPATH. I refuse to do something dangerous."
		exit -1
	fi

    mkdir -p "$OUTPUTPATH/.git"

    pushd "$OUTPUTPATH/.git"
    tar xjf "$TARPATH"
    cd ..
    git reset --hard
    rm -Rf .git
    popd

    ls -ldh "$OUTPUTPATH"
}

if [ "$#" == 0 ]
then
	PROG="$(basename $0)"
	echo "Usage: $PROG <directory> to compress"
	echo "       $PROG <file>.gitar to decompress"
	exit -1
fi

if [[ ${1#*.} == "gitar" ]] ; then
    decompress "$1"
else
    compress "$1"
fi
