#!/usr/bin/env bash

# Run curl pretending to be Chrome, but get only headers
# ------------------------------------------------------

for reqcmd in ccurl dos2unix uptoblank 
do
	command -v $reqcmd >/dev/null 2>&1 || { echo >&2 "I'm afraid this script won't be of much use to you if you don't have $reqcmd."; exit 1; }
done

ccurl -si "$@" | dos2unix -q | uptoblank
