#!/usr/bin/env bash
EXPECTED_ARGS=3
E_BADARGS=5
if [ $# -lt $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` {password} {archive filename without extension} {space-separated list of files or directories to archive}"
  exit $E_BADARGS
fi
password=$1
archive=$2
shift 2
rar a -r -rr -t -df -hp"${password}" "${archive}.rar" "$@"
