#!/usr/bin/env bash

# creates TOC files for archives

for file in $(ls *.jar 2>/dev/null)
do
  jar -tvf $file | tee $file.TOC
done

for file in $(ls *.tar.gz *.tgz 2>/dev/null)
do
  tar -ztvf $file | tee $file.TOC
done

for file in $(ls *.zip 2>/dev/null)
do
  unzip -l $file | tee $file.TOC
done

for file in $(ls *.rar 2>/dev/null)
do
  unrar l $file | tee $file.TOC
done
