#!/usr/bin/env bash

# Watches process list for items matching the given string

PROG="$(basename $0)"
if [ "$#" == 0 ]
then
	echo "Usage: $PROG <pattern>"
	exit -1
fi

watch "ps -aef | egrep -i '$1' | egrep -v 'grep|$PROG'"
