#!/usr/bin/env bash

# reinstalls a brew keg as universal
# ------------------------------------------------------------------------------------------
# Sometimes I get the message that a keg needed to be installed with the --universal option.
# This makes that easier.

MIN_ARGS=1
E_BADARGS=5
if [ $# -lt $MIN_ARGS ]
then
  echo "Usage: `basename $0` kegs"
  exit $E_BADARGS
fi
for keg in "$@"
do
	brew uninstall $keg
	brew install -vd $keg --universal
done
