#!/usr/bin/env bash

# Update stuff via zsync

EXE=zsync

command -v $EXE >/dev/null 2>&1 || { echo >&2 "I'm afraid this script won't be of much use to you if you don't have $EXE."; exit 1; }

MIN_ARGS=1
E_BADARGS=5
if [ $# -lt $MIN_ARGS ]
then
  echo "Usage: `basename $0` <file containing links>"
  exit $E_BADARGS
fi

LINKS="$1"

ZLINKS=$(grep -E '\.zsync$' $LINKS)

for URL in $ZLINKS
do
	$EXE $URL
done
