#!/usr/bin/env bash

# check for prerequisites
for reqcmd in fswatch greadlink
do
	command -v $reqcmd >/dev/null 2>&1 || { echo >&2 "I'm afraid this script won't be of much use to you if you don't have $reqcmd."; exit 1; }
done

EXPECTED_ARGS=1
E_BADARGS=5
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` {base path for rsync}"
  exit $E_BADARGS
fi

DIR=$(greadlink -f .)

fswatch -0 . | while read -d "" event
  do rsync -Phav "${event}" "$1/${event#$DIR/}"
done